# Generated by Django 5.2.8 on 2025-12-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
